#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

cd /keycloak

if [ $KEYCLOAK_USER ] && [ $KEYCLOAK_PASSWORD ]; then
    ./bin/add-user-keycloak.sh --user $KEYCLOAK_USER --password $KEYCLOAK_PASSWORD
fi

exec 2>&1

if [ -d data ]; then
  exec ./bin/standalone.sh -b=0.0.0.0 -bmanagement=0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=data -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
else
  exec ./bin/standalone.sh -b=0.0.0.0 -bmanagement=0.0.0.0
fi
