#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

cd /keycloak

if [ $KEYCLOAK_USER ] && [ $KEYCLOAK_PASSWORD ]; then
    ./bin/add-user-keycloak.sh --user $KEYCLOAK_USER --password $KEYCLOAK_PASSWORD
fi

if [ $POSTGRES_HOST ]; then
  /keycloak/bin/jboss-cli.sh --file=/setup/setup_postgresql.cli
fi

exec 2>&1
exec ./bin/standalone.sh -b=0.0.0.0 -bmanagement=0.0.0.0
